### ISSUE TITLE
About Unconditional Image  Generation.

### ISSUE THREAD

**Issue by ElegantLee** [dzld00/pytorch-manifold-matching#3]
作者您好，非常感谢您在paper中的所做的工作。在运行train.py时，有如下报错，这应该如何解决？
![QQ截图20211102170105](https://user-images.githubusercontent.com/45191822/139816867-9fe917a1-88f6-44b8-a3e3-f6c334df818d.png)
分析了一下代码，似乎是因为g_loss反向传播更新参数后，triplet_loss又更新了g_loss中的参数。

**Comment by dzld00** [comment]
原来的code适用于PyTorch1.0。刚刚在train.py里更新了适用于高版本PyTorch的写法供参考
