### ISSUE TITLE
Question about the picture of image manifold 

### ISSUE THREAD

**Issue by ElegantLee** [dzld00/pytorch-manifold-matching#6]
Hello, recently I'm thinking about how to use a graph to represent the image manifold and the process of manifold matching. It's really hard. How to draw the picture and the animation just like yours? I hope you can give me some advice !

**Comment by haibinhang** [comment]
> Hello, recently I'm thinking about how to use a graph to represent the image manifold and the process of manifold matching. It's really hard. How to draw the picture and the animation just like yours? I hope you can give me some advice !

Please send your email address to "haibin@udel.edu", and I can share my code for drawing these pics with you.
